AWSTemplateFormatVersion: 2010-09-09

Description: this template provision the nexgen prod infrastructure
  
Parameters: {}
  
Metadata: {}
  
Mappings: {}
  
Conditions: {}
  
Resources: 
  NextGenProdVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true' 
      EnableDnsHostnames: 'true'
      Tags:
      - Key: env
        Value: production
      - Key: Name
        Value: NextGenProdVPC  

  #nextgen prod vpc  webserver subnet
  NextGenProdVPCWebServerSN:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref NextGenProdVPC
      CidrBlock: 10.0.5.0/24
      Tags:
        - Key: Name
          Value: NextGenProdVPCWebServerSN
        
#Transform: {}
  
Outputs: {}